sonar.projectKey=eduai_front
sonar.projectName=EduAI Front
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=app,components,lib
sonar.exclusions=**/*.test.*,**/*.spec.*,*.db,*.json,*.txt,*.md,node_modules/**,.next/**,out/**,build/**
sonar.coverage.exclusions=**/*

# JavaScript/TypeScript specifics
sonar.typescript.tsconfigPath=tsconfig.json
