"use client"

import { useState, useEffect } from "react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { BookOpen, ThumbsUp, Search, User, FileText, ArrowRight, Link as LinkIcon, Check, Sparkles } from "lucide-react"
import Link from "next/link"
import { toast } from "sonner"
import { motion } from "framer-motion"
import { useLanguage } from "@/lib/LanguageContext"

interface PublicRepositoryProps {
  readonly user?: { readonly name: string; readonly email: string } | null
  readonly guestMode?: boolean
  readonly onLoginRequired?: () => void
  readonly onNavigateToGenerator?: () => void
  readonly onViewDashboard?: () => void
  readonly onLogout?: () => void
}

export function PublicRepository({
  user: propUser,
  guestMode: propGuestMode,
  onLoginRequired,
  onNavigateToGenerator,
  onViewDashboard,
  onLogout
}: PublicRepositoryProps = {}) {
  const { language } = useLanguage()
  const [sessions, setSessions] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState("")
  const [copiedId, setCopiedId] = useState<string | null>(null)

  const [user, setUser] = useState<{ name: string; email: string } | null>(null)
  const [guestMode, setGuestMode] = useState<boolean>(true)

  const localTranslations: Record<string, Record<string, string>> = {
    es: {
      community: "Comunidad",
      searchPlaceholder: "Buscar documentos, sesiones, temas...",
      myDashboard: "Mi Dashboard",
      createSession: "Crear Sesión",
      login: "Iniciar Sesión",
      logout: "Salir",
      heroTitle: "Aprende de los mejores ",
      heroTitleHighlight: "materiales educativos",
      heroSubtitle: "Descubre miles de sesiones de aprendizaje generadas por docentes para docentes. Listas para aplicar en tu aula.",
      whatsappPromoTitle: "¿No encuentras lo que buscas en el repositorio?",
      whatsappPromoSubtitle: "Genera tu sesión de aprendizaje personalizada al instante chateando con nuestro bot de IA en WhatsApp al ",
      whatsappPromoCTA: "Chatear con el Bot",
      popularDocs: "Documentos Populares",
      readDoc: "Leer documento",
      loadingLib: "Cargando biblioteca...",
      noDocsTitle: "No encontramos documentos",
      noDocsSubtitle: "Prueba buscar con otras palabras clave.",
      toastCopiedTitle: "¡Enlace copiado al portapapeles!",
      toastCopiedDesc: "Ahora puedes compartir esta sesión con otros docentes.",
      cycle: "Ciclo",
      hours: "h",
      anonymous: "Docente Anónimo",
      readyToApply: "Sesión de aprendizaje lista para aplicar."
    },
    en: {
      community: "Community",
      searchPlaceholder: "Search documents, sessions, topics...",
      myDashboard: "My Dashboard",
      createSession: "Create Session",
      login: "Log In",
      logout: "Log Out",
      heroTitle: "Learn from the best ",
      heroTitleHighlight: "educational materials",
      heroSubtitle: "Discover thousands of lesson plans generated by teachers for teachers. Ready to apply in your classroom.",
      whatsappPromoTitle: "Can't find what you are looking for in the repository?",
      whatsappPromoSubtitle: "Generate your custom lesson plan instantly by chatting with our AI bot on WhatsApp at ",
      whatsappPromoCTA: "Chat with Bot",
      popularDocs: "Popular Documents",
      readDoc: "Read document",
      loadingLib: "Loading library...",
      noDocsTitle: "No documents found",
      noDocsSubtitle: "Try searching with other keywords.",
      toastCopiedTitle: "Link copied to clipboard!",
      toastCopiedDesc: "Now you can share this session with other teachers.",
      cycle: "Cycle",
      hours: "h",
      anonymous: "Anonymous Teacher",
      readyToApply: "Learning session ready to apply."
    },
    qu: {
      community: "Ayllu",
      searchPlaceholder: "Qillqakunata, yachachiykunata maskay...",
      myDashboard: "Llamkana Qawana",
      createSession: "Yachachiyta Ruray",
      login: "Qillqakuy",
      logout: "Lluqsiy",
      heroTitle: "Allin yachaqkunamanta ",
      heroTitleHighlight: "yachachiy imakunata yachay",
      heroSubtitle: "Waranqantin yachachiqkunapa rurasqan yachachiykunata riqsiy. Yachachinaykipaq listo.",
      whatsappPromoTitle: "¿Manachu repositorio nisqapi maskasqaykita tarinki?",
      whatsappPromoSubtitle: "Tupachisqa yachachiyta IA bot nisqawan chateaspa WhatsApp nisqapi ruray: ",
      whatsappPromoCTA: "Bot-wan Rimay",
      popularDocs: "Riqsichisqa Qillqakuna",
      readDoc: "Qillqata ñawinchay",
      loadingLib: "Biblioteca taqichakunata cargachkan...",
      noDocsTitle: "Mana qillqakuna tarisqachu",
      noDocsSubtitle: "Huk simikunawan maskariy.",
      toastCopiedTitle: "¡T'inki chaskisqa qillqana churanaman!",
      toastCopiedDesc: "Kunanqa huk amautakunawan yachachiyta rakinakuyta atinki.",
      cycle: "Muyu",
      hours: "p.k.",
      anonymous: "Mana sutiyuq Amauta",
      readyToApply: "Yachachiy plan yachay wasipaq listo."
    },
    ay: {
      community: "Tama",
      searchPlaceholder: "Yatichawi thakhinakap maskaña...",
      myDashboard: "Lurañanakaja",
      createSession: "Yatichawi Luraña",
      login: "Mantaña",
      logout: "Mistasiriña",
      heroTitle: "Suma yatiqawinaka ",
      heroTitleHighlight: "yänakampi yatxataña",
      heroSubtitle: "Yatichirinakataki lurata yatichawi thakhinakap uñt'aña. Yatichañataki wakicht'ata.",
      whatsappPromoTitle: "¿Janiw repositorio ukan maskata tariktati?",
      whatsappPromoSubtitle: "Yatichawi IA bot-ampi WhatsApp ukan aruskipasa luram: ",
      whatsappPromoCTA: "Bot-ampi Rimt'aña",
      popularDocs: "Uñt'ata Qillqanaka",
      readDoc: "Qillqa uñakipaña",
      loadingLib: "Yatiqañ uta thakhinakap wakichaskani...",
      noDocsTitle: "Janiw qillqanaka jikxataskiti",
      noDocsSubtitle: "Yaqa arunaka lurañampi maskama.",
      toastCopiedTitle: "¡T'inki portapapeles ukar copiatañani!",
      toastCopiedDesc: "Kunanxa yaqa yatichirinakampi yatichaw chikañasiña uñacht'ayam.",
      cycle: "Muyu",
      hours: "o",
      anonymous: "Jan Uñt'at Yatichiri",
      readyToApply: "Yatichawi luraña yatiqañ utataki wakicht'ata."
    }
  }

  const lt = localTranslations[language] || localTranslations.es

  useEffect(() => {
    if (propUser === undefined) {
      const storedUser = localStorage.getItem("user")
      if (storedUser) {
        try {
          setUser(JSON.parse(storedUser))
        } catch (e) {
          console.error("Error parsing stored user", e)
        }
      }
    } else {
      setUser(propUser)
    }
  }, [propUser])

  useEffect(() => {
    if (propGuestMode === undefined) {
      const accessToken = localStorage.getItem("access_token")
      const storedUser = localStorage.getItem("user")
      setGuestMode(!(accessToken && storedUser))
    } else {
      setGuestMode(propGuestMode)
    }
  }, [propGuestMode])

  useEffect(() => {
    async function fetchPublicSessions() {
      try {
        const AUTH_URL = process.env.NEXT_PUBLIC_AUTH_URL || ""
        const res = await fetch(`${AUTH_URL}/sessions`)
        if (!res.ok) throw new Error("Error fetching sessions")
        const data = await res.json()

        let publicSessions = data.filter((s: any) => s.session_data?.is_public)

        // If no public sessions are found, just use the empty array.
        setSessions(publicSessions)
      } catch (err) {
        console.error("Failed to load public sessions:", err)
      } finally {
        setLoading(false)
      }
    }

    fetchPublicSessions()
  }, [])

  const filteredSessions = sessions.filter(s =>
    s.session_data?.tema?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    s.session_data?.author_name?.toLowerCase().includes(searchTerm.toLowerCase())
  )

  const handleCopyLink = (id: string) => {
    const link = `${globalThis.location?.origin || ""}/repositorio/${id}`
    navigator.clipboard.writeText(link)
    setCopiedId(id)
    toast.success(lt.toastCopiedTitle, {
      description: lt.toastCopiedDesc
    })
    setTimeout(() => setCopiedId(null), 3000)
  }

  return (
    <div className="min-h-screen bg-[#F8FAFC] text-slate-900 pb-20 pt-[80px]">
      {/* Header flotante */}
      <header className="fixed top-0 left-0 right-0 w-full bg-white/90 backdrop-blur-lg py-3 px-6 lg:px-12 flex items-center justify-between z-50 border-b border-slate-200/60 shadow-sm">
        <Link href="/" className="flex items-center gap-2">
          <img src="/educa-logo.png" alt="Educa +" className="h-10 md:h-12 w-auto object-contain drop-shadow-sm" />
          <span className="font-extrabold text-slate-700 text-lg tracking-tight hidden sm:inline">{lt.community}</span>
        </Link>
        <div className="flex-1 max-w-xl px-6 hidden md:block">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 h-4 w-4" />
            <input
              type="text"
              placeholder={lt.searchPlaceholder}
              className="w-full pl-10 pr-4 py-2 bg-slate-100 rounded-full text-slate-800 text-sm border-transparent focus:bg-white focus:border-blue-300 focus:ring-2 focus:ring-blue-100 transition-all outline-none"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
        </div>
        <div className="flex items-center gap-3">
          {/* Suscripciones Button */}
          <Link
            href="/suscripciones"
            className="text-slate-600 hover:text-blue-600 font-bold text-sm h-9 px-3 flex items-center gap-1.5 transition-colors"
          >
            <Sparkles className="h-4 w-4 text-blue-600" />
            Suscripciones
          </Link>

          {/* Dashboard Button */}
          <Button
            variant="ghost"
            onClick={() => {
              if (guestMode && onLoginRequired) {
                onLoginRequired()
              } else if (guestMode) {
                globalThis.location.href = "/auth"
              } else if (onViewDashboard) {
                onViewDashboard()
              } else {
                globalThis.location.href = "/?view=dashboard" // Clean route redirect
              }
            }}
            className="text-slate-600 hover:text-slate-900 font-bold text-sm h-9 px-3"
          >
            {lt.myDashboard}
          </Button>

          {/* Crear Sesion Button */}
          <Button
            onClick={() => {
              if (onNavigateToGenerator) {
                onNavigateToGenerator()
              } else {
                globalThis.location.href = "/?view=generator" // Clean route redirect
              }
            }}
            className="rounded-full bg-blue-600 text-white hover:bg-blue-700 font-bold px-4 text-xs sm:text-sm h-9 shadow-sm transition-all"
          >
            {lt.createSession}
          </Button>

          {/* User / Authentication Badge & Button */}
          {guestMode ? (
            <Button
              onClick={() => {
                if (onLoginRequired) {
                  onLoginRequired()
                } else {
                  globalThis.location.href = "/auth"
                }
              }}
              className="rounded-full bg-slate-900 text-white hover:bg-slate-800 font-bold px-4 text-xs sm:text-sm h-9 shadow-sm transition-all"
            >
              {lt.login}
            </Button>
          ) : (
            <>
              <div className="hidden sm:flex items-center gap-2 bg-slate-50 border border-slate-200 px-3 py-1.5 rounded-full shadow-sm">
                <div className="bg-blue-100 p-1 rounded-full">
                  <User className="h-3 w-3 text-blue-600" />
                </div>
                <span className="text-xs font-semibold text-slate-700 truncate max-w-[100px]">{user?.name}</span>
              </div>
              <Button
                variant="ghost"
                onClick={() => {
                  if (onLogout) {
                    onLogout()
                  } else {
                    localStorage.removeItem("user")
                    localStorage.removeItem("access_token")
                    globalThis.location.href = "/"
                  }
                }}
                className="text-red-500 hover:text-red-600 hover:bg-red-50 h-9 px-2 font-bold text-sm"
              >
                {lt.logout}
              </Button>
            </>
          )}
        </div>
      </header>

      {/* Hero Minimalista */}
      <div className="max-w-7xl mx-auto px-4 mt-8 mb-12">
        <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-3xl p-8 md:p-12 border border-blue-100/50 flex flex-col md:flex-row items-center justify-between gap-8 relative overflow-hidden">
          <div className="absolute right-0 top-0 opacity-10 pointer-events-none">
            <BookOpen className="w-96 h-96 text-blue-600 -translate-y-20 translate-x-20" />
          </div>
          <div className="z-10 max-w-2xl">
            <h1 className="text-3xl md:text-5xl font-black text-slate-800 mb-4 tracking-tight">
              {lt.heroTitle} <br /><span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">{lt.heroTitleHighlight}</span>
            </h1>
            <p className="text-lg text-slate-600 mb-6 leading-relaxed">
              {lt.heroSubtitle}
            </p>
            <div className="flex gap-4 md:hidden">
              <div className="relative w-full">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 h-4 w-4" />
                <input
                  type="text"
                  placeholder={lt.searchPlaceholder}
                  className="w-full pl-10 pr-4 py-3 bg-white shadow-sm rounded-xl text-slate-800 text-sm border-slate-200 outline-none"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                />
              </div>
            </div>
          </div>
          <div className="z-10 hidden lg:block">
            <img src="/pinguinos/pinguino_mostrando.png" className="h-48 w-48 object-contain drop-shadow-xl animate-pulse" alt="Mascota" />
          </div>
        </div>
      </div>



      <div className="max-w-7xl mx-auto px-4">
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-xl font-bold text-slate-800">{lt.popularDocs}</h2>
        </div>

        {loading && (
          <div className="flex flex-col items-center justify-center py-20">
            <img src="/pinguinos/pinguino_pensando.png" alt="Cargando" className="w-24 h-24 object-contain animate-bounce mb-4" />
            <p className="text-slate-500 font-medium">{lt.loadingLib}</p>
          </div>
        )}

        {!loading && filteredSessions.length > 0 && (
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
            {filteredSessions.map((s) => (
              <Card key={s.id} className="bg-white border-0 shadow-[0_2px_10px_-3px_rgba(6,81,237,0.1)] hover:shadow-[0_8px_30px_rgb(0,0,0,0.08)] transition-all duration-300 rounded-2xl overflow-hidden flex flex-col group cursor-pointer hover:-translate-y-1">
                {/* Portada del Documento (Simulada) */}
                <div className="aspect-[3/4] bg-slate-50 border-b border-slate-100 relative p-6 flex flex-col">
                  <div className="absolute top-4 right-4 bg-white shadow-sm border border-slate-100 px-2 py-1 rounded-md flex items-center gap-1">
                    <ThumbsUp className="h-3 w-3 text-emerald-500" />
                    <span className="text-xs font-bold text-slate-600">{s.session_data?.likes || 0}</span>
                  </div>

                  <div className="flex-1 flex flex-col justify-center">
                    <div className="bg-white p-4 rounded-lg shadow-sm border border-slate-100 transform -rotate-1 group-hover:rotate-0 transition-transform duration-300">
                      <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center mb-3">
                        <FileText className="h-4 w-4 text-blue-600" />
                      </div>
                      <h3 className="font-bold text-slate-800 text-sm line-clamp-3 leading-snug">
                        {s.session_data?.tema}
                      </h3>
                      <div className="w-12 h-1 bg-blue-500 rounded-full mt-3"></div>
                    </div>
                  </div>

                  <div className="mt-auto pt-4 flex items-center justify-between text-xs text-slate-500">
                    <div className="flex items-center gap-1 font-semibold text-indigo-600 bg-indigo-50 px-2 py-1 rounded">
                      {lt.cycle} {s.session_data?.ciclo}
                    </div>
                    <div>{s.session_data?.horasClase || 2} {lt.hours}</div>
                  </div>
                </div>

                {/* Metadatos y Acciones */}
                <CardContent className="p-4 flex-1 flex flex-col">
                  <div className="flex items-center gap-2 mb-3">
                    <div className="w-6 h-6 bg-slate-200 rounded-full flex items-center justify-center overflow-hidden">
                      <User className="h-3 w-3 text-slate-500" />
                    </div>
                    <p className="text-xs font-semibold text-slate-700 truncate">{s.session_data?.author_name || lt.anonymous}</p>
                  </div>
                  <p className="text-xs text-slate-500 line-clamp-2 mb-4 flex-1">
                    {s.session_data?.propositoSesion || lt.readyToApply}
                  </p>

                  <div className="flex items-center justify-between pt-3 border-t border-slate-100">
                    <Link href={`/repositorio/${s.id}`} className="text-blue-600 hover:text-blue-800 text-sm font-bold flex items-center gap-1 transition-colors">
                      {lt.readDoc} <ArrowRight className="h-3 w-3" />
                    </Link>
                    <button
                      onClick={(e) => { e.preventDefault(); handleCopyLink(s.id); }}
                      className="text-slate-400 hover:text-slate-700 transition-colors p-1"
                      title="Copiar enlace"
                    >
                      {copiedId === s.id ? <Check className="h-4 w-4 text-emerald-500" /> : <LinkIcon className="h-4 w-4" />}
                    </button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {!loading && filteredSessions.length === 0 && (
          <div className="text-center py-20 bg-white rounded-3xl shadow-sm border border-slate-100">
            <img src="/pinguinos/pinguino_chill.png" alt="No hay resultados" className="w-32 h-32 object-contain mx-auto mb-4 opacity-50" />
            <h3 className="text-xl font-bold text-slate-700">{lt.noDocsTitle}</h3>
            <p className="text-slate-500 mt-2">{lt.noDocsSubtitle}</p>
          </div>
        )}
      </div>
    </div>
  )
}
